// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqMY9b0Vi9ql7fAKHFx9SaqigwWB-BjUk',
    appId: '1:329558651885:web:a1d85992492a9db40bade4',
    messagingSenderId: '329558651885',
    projectId: 'ecommerce-tarek',
    authDomain: 'ecommerce-tarek.firebaseapp.com',
    storageBucket: 'ecommerce-tarek.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_VV0-LqmJn7xpqzo8vTFzKs5E9u8hCtc',
    appId: '1:329558651885:android:310d5e5545035bd20bade4',
    messagingSenderId: '329558651885',
    projectId: 'ecommerce-tarek',
    storageBucket: 'ecommerce-tarek.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHHoO2O6eX8cOCWJMzY4gfCeN5bE3aaQo',
    appId: '1:329558651885:ios:dfcc0d115a7bfc730bade4',
    messagingSenderId: '329558651885',
    projectId: 'ecommerce-tarek',
    storageBucket: 'ecommerce-tarek.appspot.com',
    iosClientId: '329558651885-qsl4m373qhebhit9i5r5rk5atg439cdc.apps.googleusercontent.com',
    iosBundleId: 'com.example.multiVendorAdmainPanel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHHoO2O6eX8cOCWJMzY4gfCeN5bE3aaQo',
    appId: '1:329558651885:ios:dfcc0d115a7bfc730bade4',
    messagingSenderId: '329558651885',
    projectId: 'ecommerce-tarek',
    storageBucket: 'ecommerce-tarek.appspot.com',
    iosClientId: '329558651885-qsl4m373qhebhit9i5r5rk5atg439cdc.apps.googleusercontent.com',
    iosBundleId: 'com.example.multiVendorAdmainPanel',
  );
}
